In [39]:
import numpy as np
import pandas as pd

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df, df1],ignore_index=True)

df = df.sample(40)

In [41]:
df.head()

,feature1,feature2,feature3,target
2,-0.367548,-1.137460,-1.322148,1
34,0.177061,-0.598109,1.226512,0
14,0.420623,0.411620,-0.071324,1
11,1.968435,-0.547788,-0.679418,1
12,-2.506230,0.146960,0.606195,1


In [47]:
# 1. Apply scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [48]:
df.iloc[:, :3] = scaler.fit_transform(df.iloc[:, :3])

In [49]:
df.head()

,feature1,feature2,feature3,target
2,-0.700809,-1.525586,-1.749156,1
34,-0.224481,-1.010757,0.491251,0
14,-0.011456,-0.046935,-0.649616,1
11,1.342296,-0.962723,-1.184163,1
12,-2.571350,-0.299561,-0.054040,1


In [52]:
# 2. Calculate covariance matrix
coMatrix = np.cov([df.iloc[:, 0], df.iloc[:, 1], df.iloc[:,2]])

In [53]:
coMatrix

array([[1.02564103, 0.20478114, 0.080118  ],
       [0.20478114, 1.02564103, 0.19838882],
       [0.080118  , 0.19838882, 1.02564103]])

Diagonal elements are the variance of 0, 1 and 2nd columns.

In [54]:
df['feature1'].var()

np.float64(1.0256410256410258)

In [56]:
# 3. Calculate eigenvectors and eigenvalues
evalues, evectors = np.linalg.eig(coMatrix)

In [60]:
evalues, evectors

(array([1.3536065 +0.j, 0.94557084+0.j, 0.77774573+0.j]),
 array([[-0.53875915+0.j, -0.69363291+0.j,  0.47813384+0.j],
        [-0.65608325+0.j, -0.01057596+0.j, -0.75461442+0.j],
        [-0.52848211+0.j,  0.72025103+0.j,  0.44938304+0.j]]))

All the values are in complex form, `real + imaginary`.  
Use `.real` to get only real part i.e. pure values

In [61]:
evalues.real

array([1.3536065 , 0.94557084, 0.77774573])

In [62]:
evectors.real

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

### Lets convert the 3d space into 2d.
## That is we are converting the 3D data into 2D with highest possible variance wich will help to preserve the maximum iinformation.

In [66]:
evectors = evectors[:2]

In [67]:
evectors

array([[-0.53875915+0.j, -0.69363291+0.j,  0.47813384+0.j],
       [-0.65608325+0.j, -0.01057596+0.j, -0.75461442+0.j]])

In [80]:
# 4. Transform the df.
new_df = np.dot(df.iloc[:, :3], evectors.T).real

In [84]:
new_df = pd.DataFrame(new_df, columns=df.iloc[:,:2].columns)

In [90]:
new_df['target'] = df['target'].values

In [91]:
new_df.head()

,feature1,feature2,target
0,0.599433,1.795862,1
1,1.056919,-0.212737,0
2,-0.271876,0.498222,1
3,-0.621586,0.023110,1
4,1.567286,1.730967,1
